export const FeedbackActionsConstants = {
  LOAD_FEEDBACK_TOPICS_IN_PROCESS: 'LOAD_FEEDBACK_TOPICS_IN_PROCESS',
  LOAD_FEEDBACK_TOPICS_SUCCESS: 'LOAD_FEEDBACK_TOPICS_SUCCESS',

  SEND_FEEDBACK_TICKET_IN_PROCESS: 'SEND_FEEDBACK_TICKET_IN_PROCESS',
  SEND_FEEDBACK_TICKET_SUCCESS: 'SEND_FEEDBACK_TICKET_SUCCESS',

  SEND_FEEDBACK_OWNER_SHIP_TICKET_IN_PROCESS: 'SEND_FEEDBACK_OWNER_SHIP_TICKET_IN_PROCESS',
  SEND_FEEDBACK_OWNER_SHIP_TICKET_SUCCESS: 'SEND_FEEDBACK_OWNER_SHIP_TICKET_SUCCESS',
};
