export const NotificationsSettingsActionsConstants = {
  GET_ACCOUNT_NOTIFICATIONS_SETTINGS_IN_PROCESS: 'GET_ACCOUNT_NOTIFICATIONS_SETTINGS_IN_PROCESS',
  GET_ACCOUNT_NOTIFICATIONS_SETTINGS_SUCCESS: 'GET_ACCOUNT_NOTIFICATIONS_SETTINGS_SUCCESS',
  SAVE_ACCOUNT_NOTIFICATIONS_SETTINGS_IN_PROCESS: 'SAVE_ACCOUNT_NOTIFICATIONS_SETTINGS_IN_PROCESS',
  SAVE_ACCOUNT_NOTIFICATIONS_SETTINGS_SUCCESS: 'SAVE_ACCOUNT_NOTIFICATIONS_SETTINGS_SUCCESS',
  CHANGE_ACCOUNT_NOTIFICATIONS_SETTINGS: 'CHANGE_ACCOUNT_NOTIFICATIONS_SETTINGS',
};
