export const PaymentsActionsConstants = {
  LOAD_PAYMENT_HISTORY_IN_PROCESS: 'LOAD_PAYMENT_HISTORY_IN_PROCESS',
  LOAD_PAYMENT_HISTORY_SUCCESS: 'LOAD_PAYMENT_HISTORY_SUCCESS',
  PAY_PAL_PAYMENT_EXECUTE_IN_PROCESS: 'PAY_PAL_PAYMENT_EXECUTE_IN_PROCESS',
  PAY_PAL_PAYMENT_CANCEL_IN_PROCESS: 'PAY_PAL_PAYMENT_CANCEL_IN_PROCESS',
  STRIPE_PAYMENT_EXECUTE_IN_PROCESS: 'STRIPE_PAYMENT_EXECUTE_IN_PROCESS',
  STRIPE_PAYMENT_CANCEL_IN_PROCESS: 'STRIPE_PAYMENT_CANCEL_IN_PROCESS',
};
