export const PromoActionsConstants = {
  LOAD_PROMO_LIST_SUCCESS: 'LOAD_PROMO_LIST_SUCCESS',
  MAKE_PROMO_CODE_IN_PROCESS: 'MAKE_PROMO_CODE_IN_PROCESS',
  MAKE_PROMO_CODE_SUCCESS: 'MAKE_PROMO_CODE_SUCCESS',
  GET_PROMO_CODE_INFO_IN_PROCESS: 'GET_PROMO_CODE_INFO_IN_PROCESS',
  GET_PROMO_CODE_INFO_SUCCESS: 'GET_PROMO_CODE_INFO_SUCCESS',
};
