export const SocialConnectActionsConstants = {
  DISCOGS_SOCIAL_CONNECT_GENERATE_URL_IN_PROCESS: 'DISCOGS_SOCIAL_CONNECT_GENERATE_URL_IN_PROCESS',
  DISCOGS_SOCIAL_CONNECT_IN_PROCESS: 'DISCOGS_SOCIAL_CONNECT_IN_PROCESS',
  DISCOGS_SOCIAL_DISCONNECT_IN_PROCESS: 'DISCOGS_SOCIAL_DISCONNECT_IN_PROCESS',
};
