export const TrendingActionsConstants = {
  GET_TRENDING_LIST_IN_PROCESS: 'GET_TRENDING_LIST_IN_PROCESS',
  GET_TRENDING_LIST_SUCCESS: 'GET_TRENDING_LIST_SUCCESS',
  PROJECTS_TRENDING_DELETE: 'PROJECTS_TRENDING_DELETE',
  PROJECTS_TRENDING_REORDER: 'PROJECTS_TRENDING_REORDER',
};
