export const UnsubscribeActionsConstants = {
  GET_UNSUBSCRIBE_TYPE_IN_PROCESS: 'GET_UNSUBSCRIBE_TYPE_IN_PROCESS',
  GET_UNSUBSCRIBE_TYPE_SUCCESS: 'GET_UNSUBSCRIBE_TYPE_SUCCESS',
  CHANGE_UNSUBSCRIBE_TYPE: 'CHANGE_UNSUBSCRIBE_TYPE',
  UNSUBSCRIBE_IN_PROCESS: 'UNSUBSCRIBE_IN_PROCESS',
};
