export const UsersActionsConstants = {
  GET_USERS_INFO_IN_PROCESS: 'GET_USERS_INFO_IN_PROCESS',
  GET_USERS_INFO_SUCCESS: 'GET_USERS_INFO_SUCCESS',
  GET_USERS_INFO_FAILED: 'GET_USERS_INFO_FAILED',
  USERS_CHANGE_FOLLOW_USER: 'USERS_CHANGE_FOLLOW_USER',
  GET_USERS_FOLLOWING_USER_IN_PROCESS: 'GET_USERS_FOLLOWING_USER_IN_PROCESS',
  GET_USERS_FOLLOWING_USER_SUCCESS: 'GET_USERS_FOLLOWING_USER_SUCCESS',
  GET_USERS_FOLLOWERS_USER_IN_PROCESS: 'GET_USERS_FOLLOWERS_USER_IN_PROCESS',
  GET_USERS_FOLLOWERS_USER_SUCCESS: 'GET_USERS_FOLLOWERS_USER_SUCCESS',
  RESET_USERS_FOLLOWERS_USER: 'RESET_USERS_FOLLOWERS_USER',
  RESET_USERS_FOLLOWING_USER: 'RESET_USERS_FOLLOWING_USER',
  USER_FOLLOW_CHANGE_FOLLOW_USER: 'USER_FOLLOW_CHANGE_FOLLOW_USER',
};
