export const VotingActionsConstants = {
  LOAD_VOTING_IN_PROCESS: 'LOAD_VOTING_IN_PROCESS',
  LOAD_VOTING_SUCCESS: 'LOAD_VOTING_SUCCESS',
  VOTE_IN_PROCESS: 'VOTE_IN_PROCESS',
  VOTE_SUCCESS: 'VOTE_SUCCESS',
  VOTE_FAILED: 'VOTE_FAILED',
};
