export const WantedActionsConstants = {
  LOAD_WANTED_IN_PROCESS: 'LOAD_WANTED_IN_PROCESS',
  LOAD_WANTED_SUCCESS: 'LOAD_WANTED_SUCCESS',
  WANTED_FILTER_SELECT: 'WANTED_FILTER_SELECT',
  WANTED_FILTER_APPLY: 'WANTED_FILTER_APPLY',
};
