const MarketplaceEvents = {
  MARKETPLACE_GOODS_WISH_ITEM_ON_SALE: 'MARKETPLACE_GOODS_WISH_ITEM_ON_SALE',
  MARKETPLACE_GOODS_USER_PURCHASE_GOODS: 'MARKETPLACE_GOODS_USER_PURCHASE_GOODS',
};

export default MarketplaceEvents;
