export const CreateProjectActionsConstants = {
  COST_CALCULATION_IN_PROCESS: 'COST_CALCULATION_IN_PROCESS',
  CREATE_PROJECT_UPDATE_AUTO_FILL: 'CREATE_PROJECT_UPDATE_AUTO_FILL',
  CREATE_PROJECT_AUTO_FILL_IN_PROCESS: 'CREATE_PROJECT_AUTO_FILL_IN_PROCESS',
  CREATE_PROJECT_AUTO_FILL_SUCCESS: 'CREATE_PROJECT_AUTO_FILL_SUCCESS',
  CREATE_PROJECT_IN_PROCESS: 'CREATE_PROJECT_IN_PROCESS',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  DELETE_PROJECT_IN_PROCESS: 'DELETE_PROJECT_IN_PROCESS',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  EDIT_PROJECT_IN_PROCESS: 'EDIT_PROJECT_IN_PROCESS',
  UPDATE_PROJECT_EXTERNAL_INFO: 'UPDATE_PROJECT_EXTERNAL_INFO',
};
