export const ProjectRipperActionsConstants = {
  ADD_PROJECT_CARD_RIPPER_INFO_IN_PROCESS: 'ADD_PROJECT_CARD_RIPPER_INFO_IN_PROCESS',
  ADD_PROJECT_CARD_RIPPER_INFO_SUCCESS: 'ADD_PROJECT_CARD_RIPPER_INFO_SUCCESS',
};
