export const SortAndFiltersActionsConstants = {
  RESET_SORT_AND_FILTERS: 'RESET_SORT_AND_FILTERS',
  GET_SORT_AND_FILTERS_IN_PROCESS: 'GET_SORT_AND_FILTERS_IN_PROCESS',
  GET_SORT_AND_FILTERS_SUCCESS: 'GET_SORT_AND_FILTERS_SUCCESS',
};
