export const CommonMessagesConstants = {
  PAY_NOW: 'Pay now',
  PREORDER: 'Pre-order',
  COMING_SOON: 'Coming soon',
  ERROR: 'Error',
  SUCCESS: 'Success',
  OK: 'Ok',
  CLOSE: 'Close',
  YES: 'Yes',
  NO: 'No',
  BUY: 'Buy',
  JOIN: 'Join',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  SAVE: 'Save',
  NO_RESULTS: 'No results',
  NO_ITEMS: 'No items',
  CONTINUE: 'Continue',
  CONFIRM: 'Confirm',
  ADD: 'Add',
  SKIP: 'Skip',
  APPLY: 'Apply',
  CHANGE: 'Change',
  REMOVE: 'Remove',
  UPGRADE_PLAN: 'Upgrade',
  READ_MORE: 'Read more',
  NOW: 'Now',
  SUBMIT: 'Submit',
  OOPS: 'Oops',

  EMAIL_CONFIRMED: 'Email confirmed successfully',

  BALANCE_UP: 'Your balance has been successfully credited',
};
