export const CommonRatingTypesConstants = {
  FOUNDER: 'FOUNDER',
  CONTRIBUTOR: 'CONTRIBUTOR',
  CONTRIBUTOR_HISTORY: 'CONTRIBUTOR_HISTORY',
  INVESTOR: 'INVESTOR',
  INVESTOR_HISTORY: 'INVESTOR_HISTORY',
  DIGGER: 'DIGGER',
  ANGEL: 'ANGEL',
  CONTRIBUTOR_BY_COLLECTED_PROJECTS: 'CONTRIBUTOR_BY_COLLECTED_PROJECTS',
};
