export const EventsActionsConstants = {
  GET_EVENTS_IN_PROCESS: 'GET_EVENTS_IN_PROCESS',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  PROJECT_NEW_CUT: 'GLOBAL_EVENTS_PROJECT_NEW_CUT',
  PROJECT_PUBLISHED: 'GLOBAL_EVENTS_PROJECT_PROJECT_PUBLISHED',
  GLOBAL_EVENT_NEW_LAST_RIPPED_PROJECT: 'GLOBAL_EVENT_NEW_LAST_RIPPED_PROJECT',
  GLOBAL_EVENT_RELOAD_LAST_RIPPED_PROJECTS: 'GLOBAL_EVENT_RELOAD_LAST_RIPPED_PROJECTS',
};
