export const GlobalActionsConstants = {
  LOAD_LANGUAGES_IN_PROCESS: 'LOAD_LANGUAGES_IN_PROCESS',
  LOAD_LANGUAGES_SUCCESS: 'LOAD_LANGUAGES_SUCCESS',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  LOAD_COUNTRIES_IN_PROCESS: 'LOAD_COUNTRIES_IN_PROCESS',
  LOAD_COUNTRIES_SUCCESS: 'LOAD_COUNTRIES_SUCCESS',
};
