export const RatingActionsConstants = {
  GET_RATING_IN_PROCESS: 'GET_RATING_IN_PROCESS',
  GET_RATING_SUCCESS: 'GET_RATING_SUCCESS',
  RATING_CHANGE_FOLLOW_USER: 'RATING_CHANGE_FOLLOW_USER',
};
