export const MarketplaceListActionsConstants = {
  SET_MARKETPLACE_PREVIEW_PURCHASED: 'SET_MARKETPLACE_PREVIEW_PURCHASED',
  TOGGLE_MARKETPLACE_PREVIEW_ALBUM_TO_CART: 'TOGGLE_MARKETPLACE_PREVIEW_ALBUM_TO_CART',
  GET_MARKETPLACE_LIST_IN_PROCESS: 'GET_MARKETPLACE_LIST_IN_PROCESS',
  GET_MARKETPLACE_LIST_SUCCESS: 'GET_MARKETPLACE_LIST_SUCCESS',
  MARKETPLACE_FILTER_SELECT: 'MARKETPLACE_FILTER_SELECT',
  MARKETPLACE_FILTER_APPLY: 'MARKETPLACE_FILTER_APPLY',
  RESET_MARKETPLACE_CURRENT_PARAMS: 'RESET_MARKETPLACE_CURRENT_PARAMS',
  SORT_SELECT: 'SORT_SELECT',
};
