export const MarketplaceCardActionsConstants = {
  SET_MARKETPLACE_CARD_PURCHASED: 'SET_MARKETPLACE_CARD_PURCHASED',
  TOGGLE_MARKETPLACE_ALBUM_TO_CART: 'TOGGLE_MARKETPLACE_ALBUM_TO_CART',
  TOGGLE_MARKETPLACE_TRACK_TO_CART: 'TOGGLE_MARKETPLACE_TRACK_TO_CART',
  GET_MARKETPLACE_CARD_IN_PROCESS: 'GET_MARKETPLACE_CARD_IN_PROCESS',
  GET_MARKETPLACE_CARD_SUCCESS: 'GET_MARKETPLACE_CARD_SUCCESS',
  ADD_MARKETPLACE_CARD_TO_WANT_IN_PROCESS: 'ADD_MARKETPLACE_CARD_TO_WANT_IN_PROCESS',
  ADD_MARKETPLACE_CARD_TO_WANT_SUCCESS: 'ADD_MARKETPLACE_CARD_TO_WANT_SUCCESS',
  DELETE_MARKETPLACE_CARD_TO_WANT_IN_PROCESS: 'DELETE_MARKETPLACE_CARD_TO_WANT_IN_PROCESS',
  DELETE_MARKETPLACE_CARD_TO_WANT_SUCCESS: 'DELETE_MARKETPLACE_CARD_TO_WANT_SUCCESS',
};
