export const MarketplaceCartActionsConstants = {
  CLEAR_MARKETPLACE_CART: 'CLEAR_MARKETPLACE_CART',
  MARKETPLACE_CART_UPDATE: 'MARKETPLACE_CART_UPDATE',
  GET_CART_INFO_IN_PROCESS: 'GET_CART_INFO_IN_PROCESS',
  GET_CART_INFO_SUCCESS: 'GET_CART_INFO_SUCCESS',
  GET_CART_IN_PROCESS: 'GET_CART_IN_PROCESS',
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  ADD_TO_CART_IN_PROCESS: 'ADD_TO_CART_IN_PROCESS',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  DELETE_TO_CART_IN_PROCESS: 'DELETE_TO_CART_IN_PROCESS',
  DELETE_TO_CART_SUCCESS: 'DELETE_TO_CART_SUCCESS',
  BUY_CART_IN_PROCESS: 'BUY_CART_IN_PROCESS',
  BUY_CART_SUCCESS: 'BUY_CART_SUCCESS',
};
