export const ConfirmPhoneActionsConstants = {
  GET_CONFIRM_PHONE_CODE_IN_PROCESS: 'GET_CONFIRM_PHONE_CODE_IN_PROCESS',
  GET_CONFIRM_PHONE_CODE_SUCCESS: 'GET_CONFIRM_PHONE_CODE_SUCCESS',
  SEND_CONFIRM_PHONE_CODE_IN_PROCESS: 'SEND_CONFIRM_PHONE_CODE_IN_PROCESS',
  SEND_CONFIRM_PHONE_CODE_SUCCESS: 'SEND_CONFIRM_PHONE_CODE_SUCCESS',
  CANCEL_CONFIRM_PHONE_CODE_IN_PROCESS: 'CANCEL_CONFIRM_PHONE_CODE_IN_PROCESS',
  CANCEL_CONFIRM_PHONE_CODE_SUCCESS: 'CANCEL_CONFIRM_PHONE_CODE_SUCCESS',
  CHANGE_CONFIRM_PHONE_EMAIL_REQUEST_LAST_DATE: 'CHANGE_CONFIRM_PHONE_EMAIL_REQUEST_LAST_DATE',
};
