export const ProjectActionsConstants = {
  GET_SHORT_PROJECT_INFO_IN_PROCESS: 'GET_SHORT_PROJECT_INFO_IN_PROCESS',
  GET_SHORT_PROJECT_INFO_SUCCESS: 'GET_SHORT_PROJECT_INFO_SUCCESS',
  CHANGE_ORDER_PROJECT_VIDEO_IN_PROCESS: 'CHANGE_ORDER_PROJECT_VIDEO_IN_PROCESS',
  CHANGE_ORDER_PROJECT_VIDEO_SUCCESS: 'CHANGE_ORDER_PROJECT_VIDEO_SUCCESS',
};
