export const ProjectRipLinkActionsConstants = {
  GET_PROJECT_RIP_LINK_BEFORE_CONFIRM_IN_PROCESS: 'GET_PROJECT_RIP_LINK_BEFORE_CONFIRM_IN_PROCESS',
  GET_PROJECT_RIP_LINK_BEFORE_CONFIRM_SUCCESS: 'GET_PROJECT_RIP_LINK_BEFORE_CONFIRM_SUCCESS',
  GET_PROJECT_RIP_LINK_CONFIRM_IN_PROCESS: 'GET_PROJECT_RIP_LINK_CONFIRM_IN_PROCESS',
  GET_PROJECT_RIP_LINK_CONFIRM_SUCCESS: 'GET_PROJECT_RIP_LINK_CONFIRM_SUCCESS',
};
