export const PersonalNotificationsSectionsConstants = {
  MY_PROJECTS: 'MY_PROJECTS',
  IN_MODERATION: 'IN_MODERATION',
  NEW_ARRIVALS: 'NEW_ARRIVALS',
  PROJECTS_EVENTS: 'PROJECTS_EVENTS',
  BALANCE: 'BALANCE',
  WITHDRAW: 'WITHDRAW',
  CASHBACK: 'CASHBACK',
  WANT_LIST_RELEASES_ITEMS: 'WANT_LIST_RELEASES_ITEMS',
  PERSONAL_EVENTS_FEED: 'PERSONAL_EVENTS_FEED',
  CONTACT_ADMIN: 'CONTACT_ADMIN',
  CUSTOM_FEED: 'CUSTOM_FEED',
};
