export const WantListReleasesItemsActionsConstants = {
  RESET_WANTLIST_RELEASE_ITEMS: 'RESET_WANTLIST_RELEASE_ITEMS',
  SEARCH_WANTLIST_RELEASE_ITEMS: 'SEARCH_WANTLIST_RELEASE_ITEMS',
  GET_WANTLIST_RELEASES_ITEM_IN_PROCESS: 'GET_WANTLIST_RELEASES_ITEM_IN_PROCESS',
  GET_WANTLIST_RELEASES_ITEM_SUCCESS: 'GET_WANTLIST_RELEASES_ITEM_SUCCESS',
  LOAD_WANTLIST_RELEASES_ITEMS_IN_PROCESS: 'LOAD_WANTLIST_RELEASES_ITEMS_IN_PROCESS',
  LOAD_WANTLIST_RELEASES_ITEMS_SUCCESS: 'LOAD_WANTLIST_RELEASES_ITEMS_SUCCESS',
  WANT_LIST_RELEASES_ITEMS_SORT_SELECT: 'WANT_LIST_RELEASES_ITEMS_SORT_SELECT',
  WANT_LIST_RELEASES_ITEMS_FILTER_SELECT: 'WANT_LIST_RELEASES_ITEMS_FILTER_SELECT',
  WANT_LIST_RELEASES_ITEMS_FILTER_APPLY: 'WANT_LIST_RELEASES_ITEMS_FILTER_APPLY',
};
