export const WantListReleaseItemActionsConstants = {
  REMOVE_WATCH_WANTLIST_RELEASE_ITEM: 'REMOVE_WATCH_WANTLIST_RELEASE_ITEM',
  ADD_WATCH_WANTLIST_RELEASE_ITEM: 'ADD_WATCH_WANTLIST_RELEASE_ITEM',
  TOGGLE_IS_ADD_RELEASE_ITEM: 'TOGGLE_IS_ADD_RELEASE_ITEM',
  GET_WANTLIST_RELEASE_ITEM_IN_PROCESS: 'GET_WANTLIST_RELEASE_ITEM_IN_PROCESS',
  GET_WANTLIST_RELEASE_ITEM_SUCCESS: 'GET_WANTLIST_RELEASE_ITEM_SUCCESS',
  CLEAR_RELEASE_ITEMS: 'CLEAR_RELEASE_ITEMS',
  UPDATE_RELEASE_ITEMS_AVAILABLE: 'UPDATE_RELEASE_ITEMS_AVAILABLE',
  LOAD_WANTLIST_RELEASE_ITEMS_IN_PROCESS: 'LOAD_WANTLIST_RELEASE_ITEMS_IN_PROCESS',
  LOAD_WANTLIST_RELEASE_ITEMS_SUCCESS: 'LOAD_WANTLIST_RELEASE_ITEMS_SUCCESS',
};
