export const PersonalUserNotificationsActionsConstants = {
  GET_PERSONAL_USER_NOTIFICATIONS_IN_PROCESS: 'GET_PERSONAL_USER_NOTIFICATIONS_IN_PROCESS',
  GET_PERSONAL_USER_NOTIFICATIONS_SUCCESS: 'GET_PERSONAL_USER_NOTIFICATIONS_SUCCESS',
  GET_SHORT_PERSONAL_USER_NOTIFICATIONS_IN_PROCESS: 'GET_SHORT_PERSONAL_USER_NOTIFICATIONS_IN_PROCESS',
  GET_SHORT_PERSONAL_USER_NOTIFICATIONS_SUCCESS: 'GET_SHORT_PERSONAL_USER_NOTIFICATIONS_SUCCESS',
  UPDATE_PERSONAL_USER_NOTIFICATIONS: 'UPDATE_PERSONAL_USER_NOTIFICATIONS',
  UPDATE_SHORT_PERSONAL_USER_NOTIFICATIONS: 'UPDATE_SHORT_PERSONAL_USER_NOTIFICATIONS',
  UPDATE_PERSONAL_USER_NOTIFICATION: 'UPDATE_PERSONAL_USER_NOTIFICATION',
};
