export const PersonalNotificationsActionsConstants = {
  GET_PERSONAL_NOTIFICATIONS_IN_PROCESS: 'GET_PERSONAL_NOTIFICATIONS_IN_PROCESS',
  GET_PERSONAL_NOTIFICATIONS_SUCCESS: 'GET_PERSONAL_NOTIFICATIONS_SUCCESS',
  DELETE_PERSONAL_NOTIFICATIONS_IN_PROCESS: 'DELETE_PERSONAL_NOTIFICATIONS_IN_PROCESS',
  DELETE_PERSONAL_NOTIFICATIONS_SUCCESS: 'DELETE_PERSONAL_NOTIFICATIONS_SUCCESS',
};
