export const PersonalNotificationCountsActionsConstants = {
  GET_UNREAD_EVENTS_IN_PROCESS: 'GET_UNREAD_EVENTS_IN_PROCESS',
  GET_UNREAD_EVENTS_SUCCESS: 'GET_UNREAD_EVENTS_SUCCESS',
  DELETE_UNREAD_EVENT_IN_PROCESS: 'DELETE_UNREAD_EVENT_IN_PROCESS',
  DELETE_UNREAD_EVENTS_SECTION: 'DELETE_UNREAD_EVENTS_SECTION',
  ADD_UNREAD_EVENT: 'ADD_UNREAD_EVENT',
  REMOVE_UNREAD_EVENT: 'REMOVE_UNREAD_EVENT',
};
