export const PurchasesActionsConstants = {
  UPDATE_PURCHASES_REQUESTS: 'UPDATE_PURCHASES_REQUESTS',
  DOWNLOAD_PURCHASES_IN_PROCESS: 'DOWNLOAD_PURCHASES_IN_PROCESS',
  GET_PURCHASES_IN_PROCESS: 'GET_PURCHASES_IN_PROCESS',
  GET_PURCHASES_SUCCESS: 'GET_PURCHASES_SUCCESS',
  GET_PURCHASE_IN_PROCESS: 'GET_PURCHASE_IN_PROCESS',
  GET_PURCHASE_SUCCESS: 'GET_PURCHASE_SUCCESS',
};
