export const WithdrawActionsConstants = {
  GET_WITHDRAW_INFO_IN_PROCESS: 'GET_WITHDRAW_INFO_IN_PROCESS',
  WITHDRAW_IN_PROCESS: 'WITHDRAW_IN_PROCESS',
  CONFIRM_WITHDRAW_IN_PROCESS: 'CONFIRM_WITHDRAW_IN_PROCESS',
  CONFIRM_WITHDRAW_SUCCESS: 'CONFIRM_WITHDRAW_SUCCESS',
  WITHDRAW_CHANGE_STATUS: 'WITHDRAW_CHANGE_STATUS',
  LOAD_WITHDRAW_HISTORY_IN_PROCESS: 'LOAD_WITHDRAW_HISTORY_IN_PROCESS',
  LOAD_WITHDRAW_HISTORY_SUCCESS: 'LOAD_WITHDRAW_HISTORY_SUCCESS',
};
