export const BlogActionsConstants = {
  LOAD_BLOG_IN_PROCESS: 'LOAD_BLOG_IN_PROCESS',
  LOAD_BLOG_SUCCESS: 'LOAD_BLOG_SUCCESS',

  LOAD_BLOG_ITEM_IN_PROCESS: 'LOAD_BLOG_ITEM_IN_PROCESS',
  LOAD_BLOG_ITEM_SUCCESS: 'LOAD_BLOG_ITEM_SUCCESS',

  LOAD_BLOG_ITEM_RELATED_ARTICLES_IN_PROCESS: 'LOAD_BLOG_ITEM_RELATED_ARTICLES_IN_PROCESS',
  LOAD_BLOG_ITEM_RELATED_ARTICLES_SUCCESS: 'LOAD_BLOG_ITEM_RELATED_ARTICLES_SUCCESS',

  LOAD_BLOG_ITEM_RELATED_PROJECTS_IN_PROCESS: 'LOAD_BLOG_ITEM_RELATED_PROJECTS_IN_PROCESS',
  LOAD_BLOG_ITEM_RELATED_PROJECTS_SUCCESS: 'LOAD_BLOG_ITEM_RELATED_PROJECTS_SUCCESS',
};
