const PromotionEventsConstants = {
  PROMOTION_POINT_USER_GOT_GEM: 'PROMOTION_POINT_USER_GOT_GEM',
  PROMOTION_POINT_USER_GOT_GOLDEN_COIN: 'PROMOTION_POINT_USER_GOT_GOLDEN_COIN',
  PROMO_ACTION_CODE_USED_REFERRAL_AGENT_GOT_REWARD: 'PROMO_ACTION_CODE_USED_REFERRAL_AGENT_GOT_REWARD',
};

export default PromotionEventsConstants;
