export const ProjectsLocationsConstants = {
  BLOG: 'BLOG',
  FUNDING_NOW: 'FUNDING_NOW',
  TRENDING: 'TRENDING',
  NEW_ARRIVALS: 'NEW_ARRIVALS',
  LATE_ENTRY: 'LATE_ENTRY',
  LATE_ENTRY_FULL: 'LATE_ENTRY_FULL',

  PROJECTS: 'PROJECTS',

  RIPPER: 'RIPPER',
  MY_PROJECTS: 'MY_PROJECTS',
  IN_MODERATION: 'IN_MODERATION',

  PROJECTS_USER: 'PROJECTS_USER',

  MY_FEED: 'CUSTOM_FEED',
};
