const ScrollBlockIdConstants = {
  BASE: 'baseId',
  FAQ: 'faqId',
  ABOUT_US: 'aboutUsId',
  FRIENDS: 'friendsId',
  CREATE_PROJECT: 'createProjectId',
  WANTLIST_RELEASES: 'wantlistReleasesId',
  WANTLIST_RELEASES_ITEMS: 'wantlistReleasesItemsId',
  WANTLIST_RELEASE_ITEMS: 'wantlistReleaseItemsId',
  PAYMENT_HISTORY: 'paymentHistoryId',
  REFERRAL: 'referralId',
  INVITES: 'invitesId',
  BALANCE: 'balanceId',
  WITHDRAW: 'withdrawId',
  PROJECT_STATS: 'projectsStatsId',
  PROJECT_CARD: 'projectCardId',
  PROJECT_COMMENTS: 'projectCardCommentsId',
  PROJECT_BALANCE: 'projectCardBalanceId',
  PROJECT_EVENT_ID: 'projectEventId',
  ACCOUNT_NOTIFICATIONS_SETTINGS: 'accountNotificationsSettingsId',
  FUNDING_NOW: 'fundingNowId',
  PROJECTS_BLOCK_ID: 'projectsBlockId',
  PROJECTS_ID: 'projectsId',
  PURCHASES_ID: 'purchasesId',
  CART_ID: 'cartId',
  MARKETPLACE_ID: 'marketplaceId',
  MARKETPLACE_TRACK_ID: 'marketplaceTrackId',
  WANTED: 'wantedId',
  USER_FOLLOWERS: 'userFollowersId',
  USER_FOLLOWING: 'userFollowingId',
  FOLLOWERS: 'followersId',
  FOLLOWING: 'followingId',
  USER_NOTIFICATIONS: 'userNotificationsId',
  USER_NOTIFICATIONS_PREVIEW: 'userNotificationsPreviewId',
  LANDING_RIP_POPUP_STEP_2: 'LandingRipPopupStep2Id',
  LANDING_RIP_STEP_2: 'LandingRipStep2Id',
  LANDING_TOOL_SECTION: 'LandingToolSectionId',
  LANDING_RIPS_SECTION: 'LandingRipsId',
  USER_PROJECTS: 'UserProjectsId',
};

export default ScrollBlockIdConstants;
