export const WebSocketChatEventsConstants = {
  CHAT_NEW_MESSAGE: 'CHAT_NEW_MESSAGE',
  CHAT_UPDATE_MESSAGE: 'CHAT_UPDATE_MESSAGE',
  CHAT_READ_MESSAGE: 'CHAT_READ_MESSAGE',
  CHAT_DELETE_MESSAGE: 'CHAT_DELETE_MESSAGE',
  CHAT_TYPING_EVENT: 'CHAT_TYPING_EVENT',
  CHAT_NEW_PARTICIPANT: 'CHAT_NEW_PARTICIPANT',
  CHAT_ENABLED_TOGGLE: 'CHAT_ENABLED_TOGGLE',
};
