export const WebSocketGlobalEventsConstants = {
  GLOBAL_EVENT_PROJECT_NEW_CUT: 'GLOBAL_EVENT_PROJECT_NEW_CUT',
  GLOBAL_EVENT_PROJECT_PROMOTION: 'GLOBAL_EVENT_PROJECT_PROMOTION',
  GLOBAL_EVENT_PROJECT_MEDIA_SECURED: 'GLOBAL_EVENT_PROJECT_MEDIA_SECURED',
  // GLOBAL_EVENT_PROJECT_PUBLISHED: 'GLOBAL_EVENT_PROJECT_PUBLISHED',
  GLOBAL_EVENT_NEW_LAST_RIPPED_PROJECT: 'GLOBAL_EVENT_NEW_LAST_RIPPED_PROJECT',
  GLOBAL_EVENT_RELOAD_LAST_RIPPED_PROJECTS: 'GLOBAL_EVENT_RELOAD_LAST_RIPPED_PROJECTS',
  GLOBAL_EVENT_MARKETPLACE_GOODS_USER_PURCHASE_GOODS: 'GLOBAL_EVENT_MARKETPLACE_GOODS_USER_PURCHASE_GOODS',
};
