export const WebSocketProjectEventsConstants = {
  PROJECT_UPDATE_BASE_INFO: 'PROJECT_UPDATE_BASE_INFO',
  PROJECT_NEW_EVENT: 'PROJECT_NEW_EVENT',
  PROJECT_NEW_CONTRIBUTOR: 'PROJECT_NEW_CONTRIBUTOR',
};
