export const VideoPlayerActionsConstants = {
  SHOW_VIDEO_PLAYER: 'SHOW_VIDEO_PLAYER',
  CLOSE_VIDEO_PLAYER: 'CLOSE_VIDEO_PLAYER',
  TOGGLE_PLAY_VIDEO_PLAYER: 'TOGGLE_PLAY_VIDEO_PLAYER',
  REMOVE_VIDEO_IN_VIDEO_PLAYER: 'REMOVE_VIDEO_IN_VIDEO_PLAYER',
  UPDATE_IN_PROCESS_VIDEO_PLAYER: 'UPDATE_IN_PROCESS_VIDEO_PLAYER',
  LISTENED_VIDEO_VIDEO_PLAYER: 'LISTENED_VIDEO_VIDEO_PLAYER',
  REMOVE_LISTENED_VIDEO_VIDEO_PLAYER: 'REMOVE_LISTENED_VIDEO_VIDEO_PLAYER',
  LOAD_NEW_DATA_IN_PROCESS: 'VIDEO_PLAYER_LOAD_NEW_DATA_IN_PROCESS',
  APPEND_DATA_TO_PLAYLIST: 'VIDEO_PLAYER_APPEND_DATA_TO_PLAYLIST',
  VIDEO_PLAYER_CHANGE_VIDEO: 'VIDEO_PLAYER_CHANGE_VIDEO',
};
